# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8332de87df62195116aa3fc9608c09f45b893f4f1f020e975edc70cfce3563dfe44605313bd6a3e4fc4acd5b91231120c85d2f6514315d4dce07d2c2a79e225

test:
  secret_key_base: dd0bd3554565f2fbed5c318618d8c05d3beeaa2b527a89b030f553cdf8accd6cbdc2e13d94df8b1b2c97e689d2cee741ec642a978337991bca18b552485b9b45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
